-- Run this in Supabase SQL Editor.
-- Keep this table private. The Vercel service-role key is the only key that
-- should be allowed to read refresh_token.
create table if not exists public.auto_renew_accounts (
    id bigint generated by default as identity primary key,
    number text not null unique,
    subscriber_id text not null default '',
    refresh_token text not null,
    option_code text not null,
    enabled boolean not null default true,
    notify_chat_id text,
    last_checked_at timestamptz,
    last_purchase_at timestamptz,
    last_status text,
    last_error text,
    locked_until timestamptz,
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create index if not exists auto_renew_accounts_enabled_idx
    on public.auto_renew_accounts (enabled);

-- Claims accounts for one cron invocation and prevents overlapping purchases.
create or replace function public.claim_auto_renew_accounts(p_lock_seconds integer default 300)
returns setof public.auto_renew_accounts
language sql
security definer
set search_path = public
as $$
    update public.auto_renew_accounts
       set locked_until = now() + make_interval(secs => p_lock_seconds),
           updated_at = now()
     where enabled = true
       and (locked_until is null or locked_until < now())
    returning *;
$$;

revoke all on function public.claim_auto_renew_accounts(integer) from public, anon, authenticated;
grant execute on function public.claim_auto_renew_accounts(integer) to service_role;

-- Optional hardening when using the service-role key through REST.
alter table public.auto_renew_accounts enable row level security;

-- Example rows (replace values; never commit real refresh tokens):
-- insert into public.auto_renew_accounts
--   (number, subscriber_id, refresh_token, option_code, notify_chat_id)
-- values ('62812...', '', 'refresh-token-1', 'option-code-1', 'telegram-chat-id');
