-- Run this in Supabase SQL Editor.
-- Keep this table private. The Vercel service-role key is the only key that
-- should be allowed to read refresh_token.
create table if not exists public.auto_renew_accounts (
    id bigint generated by default as identity primary key,
    number text not null unique,
    subscriber_id text not null default '',
    refresh_token text not null,
    option_code text not null,
    enabled boolean not null default true,
    notify_chat_id text,
    last_checked_at timestamptz,
    last_purchase_at timestamptz,
    last_status text,
    last_error text,
    locked_until timestamptz,
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);
-- Ledger for successful and attempted automatic Instagram add-on purchases.
create table if not exists public.auto_renew_transactions (
    id bigint generated by default as identity primary key,
    account_id bigint references public.auto_renew_accounts(id) on delete set null,
    number text not null,
    notify_chat_id text not null,
    option_code text not null,
    package_name text,
    status text not null check (status in ('success', 'failed')),
    amount integer not null default 0 check (amount >= 0),
    error text,
    occurred_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create index if not exists auto_renew_transactions_chat_date_idx
    on public.auto_renew_transactions (notify_chat_id, occurred_at);

create index if not exists auto_renew_transactions_number_date_idx
    on public.auto_renew_transactions (number, occurred_at);

alter table public.auto_renew_transactions enable row level security;
revoke all on table public.auto_renew_transactions from public, anon, authenticated;

create index if not exists auto_renew_accounts_enabled_idx
    on public.auto_renew_accounts (enabled);

-- Claims accounts for one cron invocation and prevents overlapping purchases.
create or replace function public.claim_auto_renew_accounts(p_lock_seconds integer default 300)
returns setof public.auto_renew_accounts
language sql
security definer
set search_path = public
as $$
    update public.auto_renew_accounts
       set locked_until = now() + make_interval(secs => p_lock_seconds),
           updated_at = now()
     where enabled = true
       and (locked_until is null or locked_until < now())
    returning *;
$$;

revoke all on function public.claim_auto_renew_accounts(integer) from public, anon, authenticated;
grant execute on function public.claim_auto_renew_accounts(integer) to service_role;

-- Optional hardening when using the service-role key through REST.
alter table public.auto_renew_accounts enable row level security;

-- Persistent Telegram bot sessions (survive Vercel deployments/restarts).
create table if not exists public.tg_user_accounts (
    id bigint generated by default as identity primary key,
    telegram_id text not null,
    number text not null,
    refresh_token text not null,
    profile jsonb not null default '{}'::jsonb,
    active boolean not null default false,
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    unique (telegram_id, number)
);

create index if not exists tg_user_accounts_telegram_idx
    on public.tg_user_accounts (telegram_id);

alter table public.tg_user_accounts enable row level security;
revoke all on table public.tg_user_accounts from public, anon, authenticated;

-- Upsert satu akun milik satu Telegram user; hanya satu row active per user.
create or replace function public.upsert_tg_user_account(
    p_telegram_id text,
    p_number text,
    p_refresh_token text,
    p_profile jsonb,
    p_active boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if p_active then
        update public.tg_user_accounts
           set active = false,
               updated_at = now()
         where telegram_id = p_telegram_id
           and active = true
           and number <> p_number;
    end if;

    insert into public.tg_user_accounts
        (telegram_id, number, refresh_token, profile, active)
    values
        (p_telegram_id, p_number, p_refresh_token, p_profile, p_active)
    on conflict (telegram_id, number) do update
        set refresh_token = excluded.refresh_token,
            profile = excluded.profile,
            active = excluded.active,
            updated_at = now();
end;
$$;

revoke all on function public.upsert_tg_user_account(text, text, text, jsonb, boolean)
    from public, anon, authenticated;
grant execute on function public.upsert_tg_user_account(text, text, text, jsonb, boolean)
    to service_role;

-- Example rows (replace values; never commit real refresh tokens):
-- insert into public.auto_renew_accounts
--   (number, subscriber_id, refresh_token, option_code, notify_chat_id)
-- values ('62812...', '', 'refresh-token-1', 'option-code-1', 'telegram-chat-id');
